# Generated by Django 5.1.6 on 2025-03-28 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student_management_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student", name="date_of_birth", field=models.TextField(),
        ),
    ]
